/**
 * MaxStarter-owned theme colors.
 * Generated by `npm run apply-maxstarter`. Do not edit by hand —
 * change public/design.md instead.
 */
export const colors = {
  primary: "#000000",
  secondary: "#FFFFFF",
  background: "#FFFFFF",
  text: "#111111",
  muted: "#6B7280",
  error: "#DC2626",
  border: "#E5E7EB",
} as const;

export type ColorToken = keyof typeof colors;
