/**
 * MaxStarter-owned typography tokens.
 * Generated by `npm run apply-maxstarter`.
 */
export const typography = {
  headingFont: "System",
  bodyFont: "System",
  sizes: {
    xs: 12,
    sm: 14,
    md: 16,
    lg: 20,
    xl: 28,
    xxl: 34,
  },
  weights: {
    regular: "400" as const,
    medium: "500" as const,
    bold: "700" as const,
  },
} as const;
