/**
 * Runtime snapshot of design.md values used by MaxStarter-owned UI sections.
 * Regenerated by apply-maxstarter — safe to overwrite.
 */
export const designContent = {
  login: {
    title: "Welcome Back",
    subtitle: "Login to continue",
  },
  home: {
    title: "Welcome",
    subtitle: "Your app is ready. Customize this screen to match your product.",
  },
  splash: {
    durationMs: 1800,
  },
} as const;
