/**
 * MaxStarter logo. Uses public/logo.png via React Native Image.
 * Regenerated by apply-maxstarter — safe to overwrite.
 * Place public/logo.svg or public/logo.png, then run apply-maxstarter.
 */
import { Image, type ImageStyle, type StyleProp } from "react-native";
import { assets } from "./assets";

export function Logo({ style }: { style?: StyleProp<ImageStyle> }) {
  return <Image source={assets.logo} style={style} resizeMode="contain" />;
}
