/**
 * Centralized asset references.
 * Logo: public/logo.png (or logo.svg). Regenerated by apply-maxstarter.
 */
export const assets = {
  logoFormat: "png" as const,
  logo: require("../../public/logo.png"),
  appName: "leave-attendance",
} as const;
